### ISSUE TITLE
improving build system

### ISSUE THREAD

**Issue by waebbl** [set-soft/tvision#1]
Hello,
I'm maintaing a package for Turbo Vision on Gentoo Linux, and I'm having a few issues with the build currently.

1. The call to ar when creating the `libtvfintl.a` static library is done via directly calling `ar`. The symbolic link of ar to the actual CHOST- prefixed ar might not exist, or might not be the binary we are looking for. It's use is discouraged in Gentoo Linux. Would it be possible, to add a search in the environment for `AR` before using plain `ar`, like you do in CheckGCC, CheckCFLAGS and others? I'd be glad to support you in this, but I don't have perl skills, but can only read and understand simple perl scripts, like the build scripts you are using, so my support could be somewhat limited. For some background on this with respect to Gentoo Linux, see https://wiki.gentoo.org/wiki/Project:Toolchain/use_native_symlinks
2. The dependency on gpm uses an automagic mechanism, i.e. if it's detected, support will be built in, if it's not detected, a warning is shown, stating that no mouse support will be available. This can cause issue when a user install's a package with gpm support and later uninstalls the package again, or decides he or she doesn't want gpm support for that package. Then gpm get's uninstalled. If, in the meantime, this user has built the tvision library, it will have gpm support built in, but the package manager doesn't know about this, because there's no flag indicating this. The same is true, if the user just doesn't want gpm support built into the library, there's currently no way to ignore gpm if it's installed on the system. After gpm get's uninstalled, the `librhtv.so` library is left in a broken state. Could you agree in adding a flag to the build system, to disable / enable support for gpm conditionally?
3. Just noticed the issue from point 2 is true for X11 and allegro as well.

Thanks for your interest.

**Comment by waebbl** [comment]
Using the below patch, detects ar defined in the environment on my x86_64 machine, and stores the correct value in the GNU_AR variable in configure.cache and also builds with this ar. Yet it doesn't output the value during configure stage properly. Maybe it's of some help. I only changed the ar value in intl/dummy/Makefile first, but this wasn't enough, c.f. https://bugs.gentoo.org/796278

```
From: Bernd Waibel <waebbl-gentoo@posteo.net>
Date: Wed, 16 Jun 2021 10:17:46 +0200
Subject: [PATCH] use proper AR

Signed-off-by: Bernd Waibel <waebbl-gentoo@posteo.net>
---
 conflib.pl          | 85 ++++++++++++++++++++++++---------------------
 intl/dummy/Makefile |  2 +-
 2 files changed, 47 insertions(+), 40 deletions(-)

diff --git a/conflib.pl b/conflib.pl
index 0abd33d..93954c4 100644
--- a/conflib.pl
+++ b/conflib.pl
@@ -1386,56 +1386,63 @@ sub LookForGNUMake
 
 sub LookForGNUar
 {
- my $test;
- print 'Looking for GNU ar: ';
+ my ($myar,$test);
 
- if ($conf{'GNU_AR'})
+ print 'Looking for GNU ar: ';
+ $myar=@conf{'GNU_AR'};
+ if ($myar)
    {
     print "$conf{'GNU_AR'} (cached)\n";
-    return $conf{'GNU_AR'};
+    return $myar;
    }
+ $myar=$ENV{'AR'};
  $conf{'UseRanLib'}=0;
- $test=RunRedirect('ar --version',$ErrorLog);
- if (($test=~/GNU ar/) || ($test=~/BSD ar/))
-   {
-    $conf{'GNU_AR'}='ar';
-    print "ar\n";
-    return 'ar';
-   }
- $test=RunRedirect('gar --version',$ErrorLog);
- if ($test=~/GNU ar/)
-   {
-    $conf{'GNU_AR'}='gar';
-    print "gar\n";
-    return 'gar';
-   }
- if (!LookForFileInPath('ar'))
+ if (!length($myar))
    {
+    $test=RunRedirect('ar --version',$ErrorLog);
+    if (($test=~/GNU ar/) || ($test=~/BSD ar/))
+      {
+        $conf{'GNU_AR'}='ar';
+       print "ar\n";
+       return 'ar';
+      }
+    $test=RunRedirect('gar --version',$ErrorLog);
+    if ($test=~/GNU ar/)
+      {
+        $conf{'GNU_AR'}='gar';
+       print "gar\n";
+       return 'gar';
+      }
+    if (!LookForFileInPath('ar'))
+      {
+       print "Unable to find GNU ar on this system.\n";
+       print "Please install it and be sure it's in your path.\n";
+       print "Also use `ar' or `gar' name for the binary.\n";
+       die;
+      }
+    # I think all ar tools are usable but ...
+    if (($OSf eq 'Darwin') || ($OSf eq 'HP-UX') || ($OSf eq 'Tru64') ||
+       ($OSf eq 'Solaris'))
+      {
+       $conf{'GNU_AR'}='ar';
+       $conf{'UseRanLib'}=1;
+       print "ar (not GNU but usable!)\n";
+       return 'ar';
+      }
+    if ($OSf eq 'QNX4')
+      {
+       $conf{'GNU_AR'}='ar';
+       $conf{'UseRanLib'}=1;
+       print "ar (WATCOM)\n";
+       return 'ar';
+      }
     print "Unable to find GNU ar on this system.\n";
     print "Please install it and be sure it's in your path.\n";
     print "Also use `ar' or `gar' name for the binary.\n";
     die;
    }
- # I think all ar tools are usable but ...
- if (($OSf eq 'Darwin') || ($OSf eq 'HP-UX') || ($OSf eq 'Tru64') ||
-     ($OSf eq 'Solaris'))
-   {
-    $conf{'GNU_AR'}='ar';
-    $conf{'UseRanLib'}=1;
-    print "ar (not GNU but usable!)\n";
-    return 'ar';
-   }
- if ($OSf eq 'QNX4')
-   {
-    $conf{'GNU_AR'}='ar';
-    $conf{'UseRanLib'}=1;
-    print "ar (WATCOM)\n";
-    return 'ar';
-   }
- print "Unable to find GNU ar on this system.\n";
- print "Please install it and be sure it's in your path.\n";
- print "Also use `ar' or `gar' name for the binary.\n";
- die;
+ $conf{'GNU_AR'}=$myar;
+ $myar;
 }
 
 sub LookForGNUinstall
diff --git a/intl/dummy/Makefile b/intl/dummy/Makefile
index c32b0a8..d47e185 100644
--- a/intl/dummy/Makefile
+++ b/intl/dummy/Makefile
@@ -2,4 +2,4 @@ RHIDE_GCC=gcc
 CC=$(RHIDE_GCC)
 
 libtvfintl.a: intldummy.o
-       ar -rv libtvfintl.a intldummy.o
+       $(AR) -rv libtvfintl.a intldummy.o
-- 
2.32.0
```

**Comment by set-soft** [comment]
Hi @waebbl !

I tested them using `AR=/usr/bin/x86_64-linux-gnu-ar ./configure --without-gpm` and the patches seems to be working, let me know if something is missing.

**Comment by waebbl** [comment]
@set-soft, looks like it's working well and as expected. Thanks for your effort!
